# 基础镜像
FROM redis
# author
MAINTAINER cold

# 挂载目录
VOLUME /home/werun/redis
# 创建目录
RUN mkdir -p /home/werun/redis
# 指定路径
WORKDIR /home/werun/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/werun/redis/redis.conf
