# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER cold

# 挂载目录
VOLUME /home/werun
# 创建目录
RUN mkdir -p /home/werun
# 指定路径
WORKDIR /home/werun
# 复制jar文件到路径
COPY ./jar/posts.jar /home/werun/posts.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","posts.jar"]